### PR TITLE
Support circe JsonCodec/ConfiguredJsonCodec macro annotations

### PR DESCRIPTION
**Pull request by tkroman**
Based on @fommil's deriving plugin (same limitations apply: no implicit resolution etc => false positives happen)

Screenshots for with/without this PR.
Notice that `ConfiguredJsonCodec`-based derivation isn't red even though it should be (no implicit `Confifuration` in scope), but I would assume it's fine with most users.

screen shot 2018-10-06 at 23 48 18
screen shot 2018-10-07 at 00 00 18

### CODE REVIEW

**Comment by jastice** [comment]
Thank you! We will have a look at this soon.

**Comment by mutcianm** [comment]
Should this also work when annotated definition already has a companion object defined in the source?

**Comment by tkroman** [comment]
@mutcianm i think this is covered by the call to `fakeCompanionClassOrCompanionClass`. Do you want a test for this?

**Comment by mutcianm** [comment]
Thanks for your contribution! Look forward to the next nightly build

**Pull request merged**
