### PR TITLE
Simplify findClasses methods in ScalaClassFinder & ScalaShortNamesCacheManager

### PR DESCRIPTION
**Pull request by sjbog**

### CODE REVIEW

**Comment by niktrop** [comment]
@sjbog Thank you for contribution, but it seems that your changes broke some tests. You may try to run "Type Inference Tests" run configuration locally to see it. 
Also, as a first time contributor, please sign our Contributor Licence Agreement: 
https://www.jetbrains.com/agreements/cla/

**Comment by sjbog** [comment]
@niktrop Aren't `JetBrains:idea183.x` branch tests broken?

**Comment by niktrop** [comment]
@sjbog Is it not working for you locally? "Type Inference Tests" should definitely pass. But I tried to apply your PR to idea191.x branch and run tests there.

**Comment by sjbog** [comment]
- [x] CI passes
- [x] CLA signed

Are there any low hanging fruits to fix? or easily verifyable / testable stuff to do

**Comment by niktrop** [comment]
Thank you for the contribution! This PR was merged in the beginning of June, sorry for the lack of updates. 
https://github.com/JetBrains/intellij-scala/commit/f2fe34bac927ccd11fd1e479498386317ccfb732 https://github.com/JetBrains/intellij-scala/commit/9cba9386214d7029bd7f728f8b53b99f17458f8d

**Pull request closed without merging**
