### PR TITLE
Scalafmt config: show nested parse error message

### PR DESCRIPTION
**Pull request by kitbellew**
Fixes [SCL-20123.](https://youtrack.jetbrains.com/issue/SCL-20123)

### CODE REVIEW

**Comment by kitbellew** [comment]
@unkarjedy PTAL, I can't test but fairly certain it should fix. Also, is 213.x still the right branch?

**Comment by unkarjedy** [comment]
Thanks!
I will look into it and manually cherry-pick the changes

>Also, is 213.x still the right branch?
It's `idea221.x` currently

**Comment by unkarjedy** [comment]
@kitbellew 
It still shows an "unknown error" prefix:
image

Why `org.scalafmt.dynamic.ScalafmtReflect#parseConfigFromString` 
returns `ScalafmtDynamicError.UnknownError` 
instead of `ScalafmtDynamicError.ConfigParseError`
like in `org.scalafmt.dynamic.ScalafmtReflect#parseConfig`
?
It looks like returning `ConfigParseError` would be the proper fix, or I do I miss anything?

Before this change
https://github.com/kitbellew/intellij-scala/commit/e394ed96e4c4edb1833d706d9ee33c01bbfa07ea#diff-7d252a166bcf0c809c86fc1ab4e6777f7cb4c007fd863a264782f860a55790e5L211
we treated any `ScalafmtConfigException` (currently non existing?) as `ConfigResolveError.ConfigParseError`

**Comment by kitbellew** [comment]
of course, i can try to fix that on the formatter side but from this end, we need to find a solution which will work reasonably well with most versions.

**Comment by unkarjedy** [comment]
JFTR we will need to update [`scalafmtVersion`](https://github.com/kitbellew/intellij-scala/blob/c76fedf08e7f1fde621d0d12d962dd6864bd343c/project/dependencies.scala#L119) when this is fixed on the formatter side

**Comment by kitbellew** [comment]
@unkarjedy if this is a direct (not dynamic) dependency, then I'll just fix the underlying exception. will ping you with pr to take a look.

**Comment by kitbellew** [comment]
superseded by #615 and scalameta/scalafmt#3192 fixes.

**Pull request closed without merging**
