### PR TITLE
Initialize reference service only once through exposed public method

### PR DESCRIPTION
**Pull request by lukaszwawrzyk**
This is the actual change we agreed on in this PR https://github.com/JetBrains/intellij-scala/pull/495
The `ScalaCompilerReferenceService.projectOpened` is extracted to a public method and we ensure that it is initialized only once.

### CODE REVIEW

**Comment by sugakandrey** [comment]
@lukaszwawrzyk Thanks, looks good to me at first glance. I'll have a closer look and hopefully merge it tomorrow.

**Comment by lukaszwawrzyk** [comment]
@sugakandrey A kind reminder :) Could you check on this PR?

**Comment by sugakandrey** [comment]
@lukaszwawrzyk I've cherry-picked your changes, they will be merged automatically after the tests on the CI are finished.

**Review by sugakandrey — APPROVED** [review]

**Comment by sugakandrey** [comment]
Merged.

**Comment by lukaszwawrzyk** [comment]
@sugakandrey Thanks! Could you let me know which version will it be in and when is it going to be released?

**Comment by sugakandrey** [comment]
@lukaszwawrzyk It's already in the nightly builds, will also be available in the next release build (whenever that might happen).

**Pull request closed without merging**
