### PR TITLE
Support .env files in Scala configurations #SCL-22463

### PR DESCRIPTION
**Pull request by andrzejressel**
Tested with SBT, ScalaTest, uTest, munit and specs2

### CODE REVIEW

**Comment by vasilmkd** [comment]
> I guess we both started working on it at the same time. Feel free to scrap mine if not needed.

Not at all! Thank you for opening this PR. How can I help you change the target to 242? What exactly was the problem? Thanks.

**Comment by andrzejressel** [comment]
Running from IDE on Windows
```
intellij-scala\scala\test-integration\testing-support\test\org\jetbrains\plugins\scala\testingSupport\ScalaTestingTestCase.scala:18:21
object profiler is not a member of package com.intellij
did you mean profile?
import com.intellij.profiler.ultimate.widget.JavaConsoleWithProfilerWidget
```

`sbt testingSupport / test` on WSL 
```
[info] compiling 216 Scala sources to intellij-scala/scala/test-integration/testing-support/target/scala-2.13/test-classes ...
[error] intellij-scala/scala/test-integration/testing-support/test/org/jetbrains/plugins/scala/testingSupport/ScalaTestingTestCase.scala:18:21: object profiler is not a member of package com.intellij
[error] did you mean profile?
[error] import com.intellij.profiler.ultimate.widget.JavaConsoleWithProfilerWidget
[error]                     ^
[error] intellij-scala/scala/test-integration/testing-support/test/org/jetbrains/plugins/scala/testingSupport/ScalaTestingTestCase.scala:144:22: not found: type JavaConsoleWithProfilerWidget
[error]         case widget: JavaConsoleWithProfilerWidget =>
[error]                      ^
[error] intellij-scala/scala/test-integration/testing-support/test/org/jetbrains/plugins/scala/testingSupport/ScalaTestingTestCase.scala:162:35: type mismatch;
[error]  found   : Any
[error]  required: com.intellij.execution.process.ProcessHandler
[error]     val exitCode = waitForTestEnd(handler, duration)
[error]                                   ^
[error] three errors found
[error] (testing-support / Test / compileIncremental) Compilation failed
[error] Total time: 40 s, completed Aug 13, 2024, 10:41:33 PM
```

I got it both on Windows and WSL2

I just realised it's only test and it makes things ever weirder. Yesterday I was getting import errors but they seem to be fixed now. I'll rebase it to 242 soon.

**Comment by andrzejressel** [comment]
I don't know - maybe today's changes somehow fixed my issues.

In any case - the issue with test and ultimate imports still exists, but commenting them out allows me to run plugin. I've retested it and seems to be working fine.

**Comment by vasilmkd** [comment]
I see. I think these are recent changes with which we have broken compilation in the community repo. Sorry about that.

Commenting out the lines seems like a good solution in the meantime.

I will do a full review shortly. Thank you again for the contribution.

**Comment by andrzejressel** [comment]
I've just realized idea itself is using XCollection annotation for serialization. Should I also use it? The array mapper result in XML looks a bit weird compared to IJ one.

**Comment by vasilmkd** [comment]
> I've just realized idea itself is using XCollection annotation for serialization. Should I also use it? The array mapper result in XML looks a bit weird compared to IJ one.

Sure, let's use `XCollection`.

I fixed the compilation problem in 242.x, the changes are currently running in the CI and will be merged soon. You should be able to rebase in about an hour.

**Comment by vasilmkd** [comment]
Please rebase on the latest `idea242.x`, the community repo can now be correctly built once again. Sorry for the inconvenience.

**Comment by andrzejressel** [comment]
I've tested it with SBT and all supported test frameworks.

I also found bug regarding SBT configuration and adding additonal env vars map (the HashMap clone).

**Comment by andrzejressel** [comment]
There is weird issue with env var duplication in XML file, but it already existed before: SCL-22947

**Comment by vasilmkd** [comment]
Hi @andrzejressel , sorry for the delay. I was waiting for IDEA 2024.3 EAP to become available. It is available from today. Can you please rebase this PR on top of `idea243.x`? We'll then get it reviewed, tested and merged. Thank you.

**Comment by andrzejressel** [comment]
@vasilmkd Done

**Comment by vasilmkd** [comment]
Great work @andrzejressel ! Thank you very much. Please do not make any changes to this PR in the next few hours. I've scheduled a build on our internal CI to run all tests. The PR will be merged automatically when all tests pass.

I'll comment on this PR at the end about the status of the ticket itself, https://youtrack.jetbrains.com/issue/SCL-22463.

**Review by vasilmkd — APPROVED** [review]

**Comment by vasilmkd** [comment]
The commit was just merged in `idea243.x`. I'm not sure why this PR wasn't automatically closed.

https://youtrack.jetbrains.com/issue/SCL-22463
This PR implemented `.env` file support for sbt and Scala test framework run configurations. I manually verified that this is now indeed the case for sbt run configurations as well as each of the following test libraries, scalatest, munit, specs2 and utest.

In the context of the ticket, .env file support should also be added to the Scala REPL and Play 2 run configurations.

@andrzejressel Would you like to continue with that? Thanks in advance.

**Comment by andrzejressel** [comment]
@vasilmkd That's very weird - I'm pretty sure I was looking for places where environmental variables are used and I only found these 2 ..

Also I cannot do Play because I think it's in closed source part.

EDIT: And REPL does not support env vars at all

**Pull request closed without merging**
