### PR TITLE
 CBT build system support

### PR DESCRIPTION
**Pull request by darthorimar**
# CBT build system support made as Google Summer of Code project

Supports openning/importing [CBT](https://github.com/cvogt/cbt/) projects, running and debugging task, etc

A little more is [here](https://github.com/darthorimar/cbt/blob/358b2a99390d442bb8bf56b7c793c7e0b0829f02/doc/intellij.md)

----

This PR is my Google Summer of Code project of Scala organization

Mentor is [Christopher Vogt](https://github.com/cvogt)

Project proposal is [here](https://docs.google.com/document/d/14BQSOKGYL9-JqrO3ZTqcCJVy2LD1JAL6nXzScxYSU-c/edit?usp=sharing)

Some releted links: [CBT Build Tool](https://github.com/cvogt/cbt), [CBT PRs connected with this project](https://github.com/cvogt/cbt/pulls?utf8=%E2%9C%93&q=%20is%3Apr%20author%3Adarthorimar%20created%3A%3E2017-06-09%20),

### CODE REVIEW

**Comment by jastice** [comment]
Thank you very much for this contribution.

We are currently blocked from merging it by several refactorings going on right now, but we are already testing it and intend to include it in the 2017.3 release.

**Comment by jcranky** [comment]
@jastice just as curiosity, when would 2017.3 be released?

**Comment by jastice** [comment]
@jcranky Somewhere around October/November. You will be able to use the cbt support in the Nightly releases before that, probably within 1-3 weeks

**Comment by jcranky** [comment]
@jastice nice, thanks :)

**Comment by jastice** [comment]
Thank you again! I merged into 2017.3 branch with a few fixes. It will become part of the 2017.3 release.

**Pull request merged**
