### PR TITLE
Add support for `back ticks` and $repo in Ammonite imports and

### PR DESCRIPTION
**Pull request by joan38**
This is making imports like the following, not red any more:
```
import $file.`download-scheduler`.DownloadModule
```

Screen Shot 2022-11-10 at 08 25 47

### CODE REVIEW

**Comment by joan38** [comment]
@vasilmkd-jetbrains can you help with this?

**Comment by unkarjedy** [comment]
@joan38 
Thanks for the PR and sorry for waiting.
We are currently in a Release process, so we don't have much resources.
I will try to take a look next week.
If it again slips my attention, please ping me again.

**Comment by unkarjedy** [comment]
LGTM
I will manually cherry-pick the change and it will be available in the next Scala Plugin Nightly version

**Comment by joan38** [comment]
Thanks!

**Pull request closed without merging**
