### PR TITLE
Bump scalameta dependency to 1.8.0

### PR DESCRIPTION
**Pull request by loskutov**
SCL-12342

### CODE REVIEW

**Comment by mutcianm** [comment]
Have you run the tests? Especially ones in `scala.meta` package.

**Comment by loskutov** [comment]
I have; some of them (`MetaAnnotationBugsTest`, which is obviously supposed to fail, and also `MetaAnnotationTests`) failed, but they also seemed to fail before the changes.

**Comment by mutcianm** [comment]
Well, none of them are supposed to fail actually. How did you run the tests?

**Comment by loskutov** [comment]
I simply used the "Run 'Tests in 'scala.meta''" option in the IDEA UI.

**Comment by mutcianm** [comment]
Okay, tests indeed pass, you've just run them incorrectly.
Merging

**Pull request merged**
