### PR TITLE
BSP import: Set language level matching JDK

### PR DESCRIPTION
**Pull request by tpasternak**

### CODE REVIEW

**Comment by jastice** [comment]
Thanks! But I think we don't necessarily want the same language level as the project jdk. I think `javaVersion` in `JvmBuildTarget` should take precedence here.

**Comment by tpasternak** [comment]
Hey, this was for project-level language version. I can setup javaVersion for modules, too. Do you know how I can test this?

**Comment by jastice** [comment]
Project-level is also not necessarily JDK version. In sbt we infer it from `javacOptions` of the root project, if available, then fall back to jdk version. Maybe we can use a similar strategy here?

**Comment by tpasternak** [comment]
Ok, now I see I probably took the wrong field again

**Comment by tpasternak** [comment]
@jastice I think it's ready now. We don't have any equivalent of root project in BSP, but we can get the version from javacOptions for each module.

**Review by jastice — APPROVED** [review]

**Pull request merged**
