### PR TITLE
Update sbt to 1.2.0

### PR DESCRIPTION
**Pull request by EnverOsmanov**

### CODE REVIEW

**Comment by jastice** [comment]
Thank you! Unfortunately we can't merge this at the moment because the Ultimate plugin build depends on certain features removed in sbt 1.0, at least until we implement a workaround.

**Comment by EnverOsmanov2** [comment]
Ultimate plugin is not this (intellij-scala) plugin, right? Is it open-source?

**Comment by EnverOsmanov** [comment]
Ultimate plugin is not this (intellij-scala) plugin, right? Is it open-source?

**Comment by jastice** [comment]
Ultimate plugin is the version of the Scala plugin distributed with the Ultimate edition of IntelliJ, and as such not open source. It depends on this one however via source dependency.

**Pull request closed without merging**
