### PR TITLE
Toggle type improvements

### PR DESCRIPTION
**Pull request by ilinum**

### CODE REVIEW

**Comment by ilinum** [comment]
@niktrop are you talking about [this](https://github.com/ilinum/intellij-scala/blob/toggle-type-second-attempt/src/org/jetbrains/plugins/scala/codeInsight/intention/types/UpdateStrategy.scala#L148) line?

I'm not filtering them out, they are a special case, I want to treat them separately

**Comment by niktrop** [comment]
In this commit https://github.com/ilinum/intellij-scala/commit/79fe915045d855491596c50f8ab75b404cc9085f you added `.filter(_.isInstanceOf[ScClass])` call. Why do you need it? As I can see case of sealed traits is not handled anywhere.

**Comment by niktrop** [comment]
Merged manually into idea16.x. Also I refactored it a bit, please take a look:
https://github.com/JetBrains/intellij-scala/commit/fd88ae745ee5c09a82311a681afdaef3b220df85

**Comment by ilinum** [comment]
@niktrop Thanks!

**Pull request closed without merging**
