### PR TITLE
ScalafmtDynamic{,Error}: remove unused classes

### PR DESCRIPTION
**Pull request by kitbellew**

### CODE REVIEW

**Comment by kitbellew** [comment]
@unkarjedy first commit. not sure how verifications are to be run here.

**Comment by unkarjedy** [comment]
@kitbellew 
Thanks!
I will look at it next week or a week after the next.
We currently have some pre-release stuff.

**Comment by kitbellew** [comment]
@unkarjedy thank you, please let me know if i can help. submitted another commit, which switches remaining code to scalafmt-dynamic 3.2.0.

I have a couple of additional, probably optional commits; please let me know if i should add them to this PR, or submit separately, later.

also, i was trying to put these commits into the 221.x branch but sbt cannot build it, some key problem. if merged into 213.x, how will this code propagate to newer releases?

**Comment by unkarjedy** [comment]
Thanks again for the PR!
I finally managed to look into it :)
LGTM

**Comment by unkarjedy** [comment]
>I have a couple of additional, probably optional commits; please let me know if i should add them to this PR, or submit separately, later

You can submit a separate PR

>also, I was trying to put these commits into the 221.x branch but sbt cannot build it, some key problem

221 branch can't be used until the first IDEA 221 EAP is publically available
You can't download Nightly IDEA version

>if merged into 213.x

You did it right, `idea213.x` branch should be used for contributions for now

>how will this code propagate to newer releases?

I will merge it manually.
We have a bot that ensures that all commits in 213.x appear in 221.x
You shouldn't bother

**Comment by kitbellew** [comment]
@unkarjedy thank you, understood. will _not_ submit for 2.12 or 2.21, only 2.13. also, will submit directly to your `idea213.x-dnaumenko` branch.

**Comment by kitbellew** [comment]
superseded by #604

**Comment by unkarjedy** [comment]
closing in favor of https://github.com/JetBrains/intellij-scala/pull/604

**Pull request closed without merging**
