### PR TITLE
Limit maximum merged module name length to less than MaxFileNameLength

### PR DESCRIPTION
**Pull request by steveniemitz**
This was merged in #621 but never made it into idea222.release.  I'm not sure if this is the right way to get it in this branch, let me know if I should do something else, thanks!

### CODE REVIEW

**Comment by jastice** [comment]
The changes do appear to be in [`idea222.release`](https://github.com/JetBrains/intellij-scala/blob/b952a5b6f26733b321706a30ce47c9a1077ae985/bsp/src/org/jetbrains/bsp/project/importing/BspResolverLogic.scala#L402-L423)

**Comment by steveniemitz** [comment]
Hm, you're right they are, https://github.com/JetBrains/intellij-scala/tree/2022.2.13 was created after though, shouldn't that commit be there?  Are those tags not being created off the release branch?

**Comment by jastice** [comment]
The tag is on the release branch, too. I can't quite explain the situation 😓

**Comment by steveniemitz** [comment]
yeah that's super weird, but its in 2022.2.16 now so I'm happy!  Thank you!

**Pull request closed without merging**
