### PR TITLE
[RDCT] GTW-1079: Fix "import element" intention fix in RemoteDev setup

### PR DESCRIPTION
**Pull request by gabrielrussoc**
Backports the fix (a89a1c1e3de4074a60aecb5bc54f927a7392251f) of https://youtrack.jetbrains.com/issue/GTW-1079/RD-Import-suggestions-are-broken-for-scala to 2024.2

Original text:

Direct UI checks like `editor.getContentComponent.isFocusOwner` and `editor.getScrollingModel.getVisibleArea` do not return any meaningful results in case of a remote scenario. This commit replaces `isFocusOwner` with `UIUtil.isShowing`, which is RemoteDev-aware API, and handling some cases directly for `AppMode.isRemoteDevHost`.

---

I tested this by building the plugin on top of my changes, installing it from disk and verifying the "Import class" behaviour now works as expected in 2024.2:

https://github.com/user-attachments/assets/2ca8efcc-bd6a-4044-9269-4e2393650068

### CODE REVIEW

**Comment by gabrielrussoc** [comment]
@slavam2605 does this look reasonable? I can't request reviewers

**Comment by timaliberdov** [comment]
Thank you. I will merge the change by running it through our CI.

**Comment by timaliberdov** [comment]
It's included in the latest `idea242.x`.

**Comment by gabrielrussoc** [comment]
@timaliberdov awesome, thanks!

When should we expect this to be released ?

**Comment by timaliberdov** [comment]
@gabrielrussoc it should be available in the next 2024.2 nightly. Probably tomorrow.

**Pull request closed without merging**
