### PR TITLE
HOCON editor improvements

### PR DESCRIPTION
**Pull request by ghik**
Primary motivation for this PR is a bunch of relatively small editor features but also some unrelated fixes and refactorings have been piggybacked.

In detail, this PR contains:

Features:
- Joining lines and hitting enter now work properly in HOCON comments (i.e. like in other languages).
  hocomments
- HOCON files now have breadcrumbs displayed above the editor like for JSON and XML files.
  hobreadcrumbs
- Keys that have the same full path are highlighted (like highlight usages):
  hoghlight
- Implementation of move statement action (Ctrl+Shift+Up/Down) which is able to move around object entries. It can also move object fields into and out of other objects by removing or adding appropriate path prefix:
  homove

Include resolution improvements:
- Relative includes now also work outside of source or library files
- Resolved files are sorted so that `.conf` files come first, `.json` after them and `.properties` at the end - this reflects the way Typesafe Config merges them
- Fixed search scope (problems with transitive dependencies)
- Implemented test suite with tests for complex project structure (multiple modules with libraries)

Internal refactors needed by features listed above and potential future features:
- Grammar changes:
  - Changed parsing of object fields - introduced "prefixed field" (key-dot-nextField) and "valued field" (key-value) instead of using path-value pair.
  - Introduced separate element types and PSI classes for strings in different contexts (key, value, include)
  - Changed binding of documentation comments so that it's a bit more like in Java/Scala
- Refactored and expanded test suite
- Expanded API of PSI elements

### CODE REVIEW

**Comment by jozic** [comment]
very nice set of improvements, would love to see it merged

**Comment by ktoso** [comment]
These are changes awesome, :+1:  :-)

**Comment by ghik** [comment]
Thanks guys! I hope to soon implement stuff like autocompletion, documentation lookup, navigation through substitutions, etc.

**Comment by He-Pin** [comment]
Reallly really help for play/akka development,heavy used the typesafe-config.thank you very much. :100:

**Comment by Lugzan** [comment]
Great work!

**Comment by He-Pin** [comment]
@ghik how about fix the copy reference thing?
it currently give me `reference.conf:81` not something like `gate.prod.url`

**Comment by ghik** [comment]
@hepin1989 I've pretty much done it. PR will be submitted soon (after I've finished fighting with tests...)

**Pull request merged**
