### PR TITLE
ScalaBundle: remove redundant scalafmt message

### PR DESCRIPTION
**Pull request by kitbellew**
Instead of `scalafmt.config.load.errors.file.not.found`, which is not very informative and referenced only once, switch to the message which is used in all other cases: `scalafmt.can.not.find.config.file`.

### CODE REVIEW

**Comment by kitbellew** [comment]
@unkarjedy fyi

**Comment by kitbellew** [comment]
should i update this?

**Comment by unkarjedy** [comment]
@kitbellew 
I will look into it.
I also saw a notification about your comment
>so even though that case class has correct hashcode and equals...

Was it intentionally deleted? I cna't find it on GitHub

**Comment by kitbellew** [comment]
sorry, i deleted the comment when i realized it was not about whether the key works in the map, but whether the map can be serialized -- or restored from current cache which used a string...

**Comment by kitbellew** [comment]
superseded by #615.

**Pull request closed without merging**
