### PR TITLE
ScalafmtDynamicConfigService: parse config once

### PR DESCRIPTION
**Pull request by kitbellew**
Also, in `ScalafmtDynamic`, use the parsed `ScalafmtVersion`.

### CODE REVIEW

**Comment by kitbellew** [comment]
@unkarjedy fyi.

i accidentally pushed this on top of the original PR, which now contains 4 commits, 2 of which had already been merged into your branch; this is an incremental copy and should be considered instead.

**Comment by unkarjedy** [comment]
Thanks!
Manually cherry-picked to personal branch and merged into `idea213.x` (with some fixes in extra commits)
This will also be included to `idea221`.

**Comment by kitbellew** [comment]
thank you! what did I miss (you mentioned fixes)?

**Comment by unkarjedy** [comment]
Fixes:
https://github.com/JetBrains/intellij-scala/commit/3758f48296159404cc23375f2922c081f2037b07#diff-7da0d534f3a8b12bc72cca83ebd29addcc23a0f0f558310a11fcf7aaa61ba3d2R261
https://github.com/JetBrains/intellij-scala/commit/75214a68cdcc1e87a5a82c0c16993d30ea9ae39b

**Comment by unkarjedy** [comment]
JFTR: looks like leads to https://youtrack.jetbrains.com/issue/SCL-20123

**Comment by kitbellew** [comment]
@unkarjedy I'll take a look over the weekend

**Pull request closed without merging**
